spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
